name: nigma2020
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_spinkit:
  flutter_custom_clippers:
  font_awesome_flutter:
  fancy_bottom_navigation:
  url_launcher:
  firebase_auth:
  firebase_messaging:
  firebase_database:
  path_provider: ^1.5.1
  cloud_firestore:
  sliding_up_panel:
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - images/warn.png
   - images/nigma.jpeg
   - images/sam.jpeg
   - images/slogo.jpeg
   - images/n1.gif
   - images/addBook.png
   - images/splash.png
   - images/splash1.gif
   - images/bell.gif
   - images/s1.gif
   - images/loader.gif
   - images/mobile.png
   - images/done.gif
   - images/spin.gif
   - images/all/cyber1.png
   - images/all/dance1.png
   - images/all/dance2.png
   - images/all/draw1.png
   - images/all/draw2.png
   - images/all/finance1.png
   - images/all/hr1.png
   - images/all/hr2.png
   - images/all/hr3.png
   - images/all/ice1.png
   - images/all/manager1.png
   - images/all/manager2.png
   - images/all/market1.png
   - images/all/market2.png
   - images/all/market3.png
   - images/all/market4.png
   - images/all/math1.png
   - images/all/math2.png
   - images/all/mock1.png
   - images/all/mock2.png
   - images/all/mock3.png
   - images/all/mock4.png
   - images/all/photo1.png
   - images/all/photo2.png
   - images/all/photo3.png
   - images/all/quiz1.png
   - images/all/quiz2.png
   - images/all/rody1.png
   - images/all/rody2.png
   - images/all/song1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
